# Agentic Trader Platform - Start All Services
# This script starts all required services with proper port configuration

Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  🚀 Starting Agentic Trader Platform Services" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

# Find available ports
function Find-FreePort($startPort, $endPort) {
    for ($port = $startPort; $port -le $endPort; $port++) {
        $inUse = Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue
        if (-not $inUse) {
            return $port
        }
    }
    return $null
}

$backendPort = Find-FreePort 8001 8100
$frontendPort = Find-FreePort 5174 5200

if (-not $backendPort -or -not $frontendPort) {
    Write-Host "❌ Could not find free ports!" -ForegroundColor Red
    exit 1
}

Write-Host "📦 Found Ports:" -ForegroundColor Yellow
Write-Host "   Backend:  $backendPort" -ForegroundColor White
Write-Host "   Frontend: $frontendPort" -ForegroundColor White
Write-Host ""

# Start Docker infrastructure
Write-Host "🐳 Starting Docker infrastructure..." -ForegroundColor Yellow
docker-compose up -d postgres redis clickhouse chromadb redpanda

Write-Host "⏳ Waiting for database..." -ForegroundColor Yellow
Start-Sleep -Seconds 10

# Create frontend env with correct ports
$envContent = @"
# Auto-generated by start-services.ps1
VITE_API_URL=http://localhost:$backendPort
VITE_WS_URL=ws://localhost:$backendPort/ws/public
"@
$envContent | Out-File -FilePath "frontend/.env.local" -Encoding UTF8 -Force
Write-Host "✅ Updated frontend/.env.local" -ForegroundColor Green

# Start Backend
Write-Host ""
Write-Host "⚙️  Starting Backend on port $backendPort..." -ForegroundColor Yellow
$backendProcess = Start-Process -FilePath "powershell" -ArgumentList "-Command", "`$env:PYTHONPATH='$PWD'; cd '$PWD'; .\venv\Scripts\activate; uvicorn backend.api.main:app --reload --port $backendPort" -PassThru -WindowStyle Hidden
Write-Host "✅ Backend started (PID: $($backendProcess.Id))" -ForegroundColor Green

# Wait for backend
Start-Sleep -Seconds 5

# Start Frontend
Write-Host ""
Write-Host "🎨 Starting Frontend on port $frontendPort..." -ForegroundColor Yellow
$frontendProcess = Start-Process -FilePath "powershell" -ArgumentList "-Command", "cd '$PWD\frontend'; npm run dev -- --port $frontendPort" -PassThru -WindowStyle Hidden
Write-Host "✅ Frontend started (PID: $($frontendProcess.Id))" -ForegroundColor Green

# Save PIDs for shutdown
@"
Backend PID: $($backendProcess.Id)
Frontend PID: $($frontendProcess.Id)
Backend Port: $backendPort
Frontend Port: $frontendPort
"@ | Out-File -FilePath ".service-pids" -Encoding UTF8

# Final status
Start-Sleep -Seconds 3
Write-Host ""
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  ✅ ALL SERVICES STARTED!" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  🔗 URLs:" -ForegroundColor Yellow
Write-Host "     • Backend API:  http://localhost:$backendPort" -ForegroundColor White
Write-Host "     • API Docs:     http://localhost:$backendPort/docs" -ForegroundColor White
Write-Host "     • Frontend:     http://localhost:$frontendPort" -ForegroundColor White
Write-Host "     • Paper Trading: http://localhost:$frontendPort/paper-trading" -ForegroundColor White
Write-Host ""
Write-Host "  🛑 To stop services, run: ./stop-services.ps1" -ForegroundColor Red
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan

# Keep script running
Write-Host ""
Write-Host "Press Ctrl+C to stop viewing logs (services keep running)" -ForegroundColor DarkGray
while ($true) {
    Start-Sleep -Seconds 5

    # Check if processes are still running
    $backendRunning = Get-Process -Id $backendProcess.Id -ErrorAction SilentlyContinue
    $frontendRunning = Get-Process -Id $frontendProcess.Id -ErrorAction SilentlyContinue

    if (-not $backendRunning) {
        Write-Host "⚠️  Backend stopped!" -ForegroundColor Red
        break
    }
    if (-not $frontendRunning) {
        Write-Host "⚠️  Frontend stopped!" -ForegroundColor Red
        break
    }
}
