global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-server'
    static_configs:
      - targets: ['api-server:8000']

  - job_name: 'trading-engine'
    static_configs:
      - targets: ['trading-engine:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']  # Interne Docker poort, extern is 5000
