"""Analytics export functionality."""

import json
from datetime import datetime
from typing import Dict, Any, List, Optional


class AnalyticsExporter:
    """
    Exports analytics reports in various formats.
    
    Supported formats:
    - JSON (detailed)
    - HTML (formatted report)
    - PDF (formatted report)
    """
    
    def __init__(self):
        self.supported_formats = ["json", "html", "pdf"]
    
    def export_analytics(
        self,
        metrics: Dict[str, Any],
        format: str = "json",
        user_name: str = "Trader",
    ) -> bytes:
        """
        Export analytics to specified format.
        
        Args:
            metrics: Analytics metrics dictionary
            format: Export format (json, html, pdf)
            user_name: User name for report header
            
        Returns:
            Exported data as bytes
        """
        format = format.lower()
        
        if format == "json":
            return self._export_json(metrics)
        elif format == "html":
            return self._export_html(metrics, user_name)
        elif format == "pdf":
            return self._export_pdf(metrics, user_name)
        else:
            raise ValueError(f"Unsupported format: {format}")
    
    def _export_json(self, metrics: Dict[str, Any]) -> bytes:
        """Export analytics to JSON format."""
        data = {
            "exported_at": datetime.utcnow().isoformat(),
            "metrics": metrics,
        }
        return json.dumps(data, indent=2).encode("utf-8")
    
    def _export_html(self, metrics: Dict[str, Any], user_name: str) -> bytes:
        """Export analytics to HTML report."""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Trading Analytics Report - {user_name}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            background: #f5f5f5;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #333;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #555;
            margin-top: 30px;
        }}
        .metric-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }}
        .metric-card {{
            background: #f9f9f9;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #4CAF50;
        }}
        .metric-label {{
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
        }}
        .metric-value {{
            font-size: 24px;
            font-weight: bold;
            color: #333;
            margin-top: 5px;
        }}
        .positive {{
            color: #4CAF50;
        }}
        .negative {{
            color: #f44336;
        }}
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #999;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Trading Analytics Report</h1>
        <p><strong>Trader:</strong> {user_name}</p>
        <p><strong>Generated:</strong> {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
        
        <h2>Performance Metrics</h2>
        <div class="metric-grid">
            {self._generate_metric_cards(metrics)}
        </div>
        
        <div class="footer">
            Generated by Agentic Trader Platform
        </div>
    </div>
</body>
</html>
"""
        return html.encode("utf-8")
    
    def _generate_metric_cards(self, metrics: Dict[str, Any]) -> str:
        """Generate HTML for metric cards."""
        cards = []
        
        metric_display = {
            "total_trades": ("Total Trades", "", "number"),
            "win_rate": ("Win Rate", "%", "percentage"),
            "total_pnl": ("Total P&L", " EUR", "currency"),
            "avg_pnl_per_trade": ("Avg P&L/Trade", " EUR", "currency"),
            "sharpe_ratio": ("Sharpe Ratio", "", "number"),
            "max_drawdown": ("Max Drawdown", "%", "percentage"),
            "profit_factor": ("Profit Factor", "", "number"),
            "best_trade": ("Best Trade", " EUR", "currency"),
            "worst_trade": ("Worst Trade", " EUR", "currency"),
        }
        
        for key, (label, suffix, format_type) in metric_display.items():
            if key in metrics:
                value = metrics[key]
                
                if format_type == "percentage":
                    formatted = f"{value:.2f}"
                    css_class = "positive" if value > 50 else "negative"
                elif format_type == "currency":
                    formatted = f"{value:,.2f}"
                    css_class = "positive" if value > 0 else "negative" if value < 0 else ""
                else:
                    formatted = f"{value:.2f}" if isinstance(value, float) else str(value)
                    css_class = ""
                
                cards.append(f"""
                <div class="metric-card">
                    <div class="metric-label">{label}</div>
                    <div class="metric-value {css_class}">{formatted}{suffix}</div>
                </div>
                """)
        
        return "\n".join(cards)
    
    def _export_pdf(self, metrics: Dict[str, Any], user_name: str) -> bytes:
        """
        Export analytics to PDF.
        
        Note: This is a placeholder. In production, use reportlab or weasyprint.
        """
        # For now, return HTML with PDF content-type note
        html = self._export_html(metrics, user_name)
        return html
    
    def generate_leaderboard_export(
        self,
        leaderboard: List[Dict[str, Any]],
        format: str = "json",
    ) -> bytes:
        """Export leaderboard data."""
        data = {
            "exported_at": datetime.utcnow().isoformat(),
            "leaderboard_size": len(leaderboard),
            "rankings": leaderboard,
        }
        
        if format == "json":
            return json.dumps(data, indent=2).encode("utf-8")
        elif format == "csv":
            import csv
            from io import StringIO
            
            output = StringIO()
            if leaderboard:
                writer = csv.DictWriter(output, fieldnames=leaderboard[0].keys())
                writer.writeheader()
                writer.writerows(leaderboard)
            
            return output.getvalue().encode("utf-8")
        else:
            raise ValueError(f"Unsupported format: {format}")


# Global exporter instance
analytics_exporter = AnalyticsExporter()
