"""
LLM Reflection Engine - Echte AI-generated self-improvement

Gebruikt LLM (Ollama/DeepSeek) om:
1. Reflections te genereren obv performance
2. Strategieën aan te passen
3. Confidence te calibreren
"""

import json
import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional

from backend.core.llm.llm_provider import LLMBackend, create_llm_provider

logger = logging.getLogger(__name__)


@dataclass
class LLMReflection:
    """Reflection generated by LLM."""

    agent_name: str
    timestamp: str
    reflection_text: str
    identified_bias: str
    suggested_adjustment: str
    new_confidence_multiplier: float
    reasoning_quality_score: int  # 1-10
    lesson_for_next_trade: str


class LLMReflectionEngine:
    """
    Engine voor LLM-gegenereerde reflections.
    """

    REFLECTION_PROMPT_TEMPLATE = """Je bent een trading performance coach. Analyseer de performance van {agent_name} en geef een gedetailleerde reflection.

AGENT: {agent_name}
SYMBOL: {symbol}
RECENTE PERFORMANCE (laatste {trade_count} trades):
{trade_history}

OVERALL STATS:
- Winrate: {winrate:.1%}
- Gemiddelde PnL: {avg_pnl:+.4f}
- Totale PnL: {total_pnl:+.4f}
- Meest voorkomende actie: {common_action}
- Huidige confidence multiplier: {current_mult:.2f}

MARKET CONTEXT:
- Huidig regime: {regime}
- RSI: {rsi}
- ADX: {adx}

OPDRACHT:
1. Analyseer waarom de agent goed/slecht heeft gepresteerd
2. Identificeer specifieke biases (te veel BUY/SELL/HOLD, te hoge/lage confidence)
3. Stel een concrete aanpassing voor
4. Geef een les voor de volgende trade

OUTPUT JSON:
{{
    "reflection": "string - gedetailleerde analyse",
    "identified_bias": "string - specifieke bias",
    "suggested_adjustment": "string - concrete aanpassing",
    "new_confidence_multiplier": float (0.5-1.5),
    "reasoning_quality_score": int (1-10),
    "lesson_for_next_trade": "string - kernboodschap"
}}"""

    def __init__(self, backend: str = "ollama", model: str = "llama3.2"):
        """Initialize met LLM provider."""
        try:
            self.llm = create_llm_provider(backend=backend, model=model)
            self.backend = backend
            logger.info(f"LLM Reflection Engine initialized with {backend}/{model}")
        except Exception as e:
            logger.error(f"Failed to init LLM: {e}")
            self.llm = None
            self.backend = None

    def generate_reflection(
        self, agent_name: str, symbol: str, recent_trades: List[Dict], market_state: Dict
    ) -> Optional[LLMReflection]:
        """
        Generate LLM reflection voor een agent.
        """
        if not self.llm:
            logger.warning("LLM not available, using fallback reflection")
            return self._fallback_reflection(agent_name, recent_trades)

        # Bereken stats
        stats = self._calculate_stats(recent_trades)

        # Format trade history
        trade_history = self._format_trade_history(recent_trades[-10:])  # Laatste 10

        # Build prompt
        prompt = self.REFLECTION_PROMPT_TEMPLATE.format(
            agent_name=agent_name,
            symbol=symbol,
            trade_count=len(recent_trades),
            trade_history=trade_history,
            winrate=stats["winrate"],
            avg_pnl=stats["avg_pnl"],
            total_pnl=stats["total_pnl"],
            common_action=stats["common_action"],
            current_mult=stats.get("current_mult", 1.0),
            regime=market_state.get("regime", "unknown"),
            rsi=market_state.get("rsi", 50),
            adx=market_state.get("adx", 20),
        )

        try:
            # Call LLM
            logger.info(f"Generating LLM reflection for {agent_name}...")
            response = self.llm.generate(
                prompt=prompt,
                system_prompt="Je bent een expert trading coach die agents helpt verbeteren.",
                temperature=0.3,
            )

            # Parse response
            if isinstance(response, dict) and "text" in response:
                # Extract JSON from response
                text = response["text"]
                # Find JSON block
                if "```json" in text:
                    json_str = text.split("```json")[1].split("```")[0].strip()
                elif "```" in text:
                    json_str = text.split("```")[1].split("```")[0].strip()
                else:
                    json_str = text.strip()

                data = json.loads(json_str)

                reflection = LLMReflection(
                    agent_name=agent_name,
                    timestamp=datetime.now().isoformat(),
                    reflection_text=data.get("reflection", ""),
                    identified_bias=data.get("identified_bias", "None"),
                    suggested_adjustment=data.get("suggested_adjustment", ""),
                    new_confidence_multiplier=float(data.get("new_confidence_multiplier", 1.0)),
                    reasoning_quality_score=int(data.get("reasoning_quality_score", 5)),
                    lesson_for_next_trade=data.get("lesson_for_next_trade", ""),
                )

                logger.info(
                    f"Reflection generated for {agent_name}: "
                    f"bias={reflection.identified_bias}, "
                    f"new_mult={reflection.new_confidence_multiplier:.2f}"
                )

                return reflection

        except Exception as e:
            logger.error(f"LLM reflection failed: {e}")
            return self._fallback_reflection(agent_name, recent_trades)

    def _fallback_reflection(self, agent_name: str, trades: List[Dict]) -> LLMReflection:
        """Fallback als LLM niet beschikbaar is."""
        stats = self._calculate_stats(trades)

        if stats["winrate"] > 0.6:
            reflection = f"Goede performance ({stats['winrate']:.0%}). Blijf consistent."
            bias = "Geen significante bias"
            mult = 1.1
        elif stats["winrate"] < 0.4:
            reflection = f"Slechte performance ({stats['winrate']:.0%}). Wees conservatiever."
            bias = "Mogelijk te veel risico"
            mult = 0.8
        else:
            reflection = "Gemiddelde performance. Focus op consistentie."
            bias = "Geen duidelijke bias"
            mult = 1.0

        return LLMReflection(
            agent_name=agent_name,
            timestamp=datetime.now().isoformat(),
            reflection_text=reflection,
            identified_bias=bias,
            suggested_adjustment=(
                "Pas confidence aan obv performance"
                if stats["winrate"] < 0.5
                else "Handhaaf huidige strategie"
            ),
            new_confidence_multiplier=mult,
            reasoning_quality_score=5,
            lesson_for_next_trade="Blijf alert en leer van fouten",
        )

    def _calculate_stats(self, trades: List[Dict]) -> Dict:
        """Calculate performance stats."""
        if not trades:
            return {
                "winrate": 0.5,
                "avg_pnl": 0.0,
                "total_pnl": 0.0,
                "common_action": "HOLD",
                "current_mult": 1.0,
            }

        wins = sum(1 for t in trades if t.get("pnl", 0) > 0)
        actions = [t.get("action", "HOLD") for t in trades]
        common_action = max(set(actions), key=actions.count) if actions else "HOLD"

        return {
            "winrate": wins / len(trades),
            "avg_pnl": sum(t.get("pnl", 0) for t in trades) / len(trades),
            "total_pnl": sum(t.get("pnl", 0) for t in trades),
            "common_action": common_action,
            "current_mult": trades[-1].get("confidence_mult", 1.0) if trades else 1.0,
        }

    def _format_trade_history(self, trades: List[Dict]) -> str:
        """Format trade history voor prompt."""
        lines = []
        for i, trade in enumerate(trades, 1):
            lines.append(
                f"{i}. {trade.get('action', 'HOLD')} | "
                f"PnL: {trade.get('pnl', 0):+.4f} | "
                f"Conf: {trade.get('confidence', 0):.2f} | "
                f"{trade.get('symbol', 'UNKNOWN')}"
            )
        return "\n".join(lines)

    def generate_strategy_evolution(self, agent_name: str, performance_history: List[Dict]) -> str:
        """
        Generate lang-term strategie evolution advies.
        """
        if not self.llm:
            return "LLM niet beschikbaar voor strategie evolution"

        prompt = f"""Analyiseer de langetermijn evolutie van {agent_name}.

PERFORMANCE HISTORY (laatste {len(performance_history)} trades):
{self._format_trade_history(performance_history[-20:])}

Geef een strategie evolution plan:
1. Wat werkt goed en moet behouden blijven?
2. Wat moet veranderen?
3. Welke nieuwe technieken zouden helpen?

Output: korte, concrete aanbevelingen."""

        try:
            response = self.llm.generate(prompt, temperature=0.4)
            if isinstance(response, dict) and "text" in response:
                return response["text"]
        except Exception as e:
            logger.error(f"Strategy evolution failed: {e}")

        return "Blijf consistent en analyseer verliezers kritisch."


# Singleton instance
_llm_engine = None


def get_llm_reflection_engine(
    backend: str = "ollama", model: str = "llama3.2"
) -> LLMReflectionEngine:
    """Get singleton LLM reflection engine."""
    global _llm_engine
    if _llm_engine is None:
        _llm_engine = LLMReflectionEngine(backend=backend, model=model)
    return _llm_engine
