"""
Self-Improving Prompts - Dynamic Agent Reflection

Elke agent krijgt zijn eigen historische performance mee in de prompt
en genereert een reflection op basis van recente trades.
"""

import json
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List, Optional


@dataclass
class AgentReflection:
    """Reflection generated by agent about its own performance."""

    timestamp: str
    agent_name: str
    recent_winrate: float
    recent_pnl: float
    lessons_learned: str
    strategy_adjustment: str
    confidence_adjustment: float  # Multiplier voor volgende trades
    bias_acknowledged: Optional[str]  # Bv "Te veel SELL", "Te laag conf"


class SelfImprovingPromptBuilder:
    """Builds dynamic prompts with performance feedback."""

    # Templates per agent type
    SENTIMENT_PROMPT_TEMPLATE = """Je bent {agent_name}, een sentiment analyse agent.

📊 JOUW RECENTE PERFORMANCE (laatste 20 trades):
- Winrate: {winrate:.1%}
- Gemiddelde P&L: {avg_pnl:+.4f}
- Totale trades: {total_trades}
- Meest voorkomende actie: {common_action} ({common_pct:.0%})

🎯 REFLECTION:
{reflection_text}

⚠️ GEIDENTIFICEERDE BIAS:
{bias_warning}

📈 STRATEGIE AANPASSING:
{strategy_adjustment}

💡 OPDRACHT:
Analyseer het sentiment voor {symbol}. Je confidence is aangepast met factor {confidence_mult:.2f}.
Wees kritisch op je eigen eerdere calls. Als je recent vaak fout zat, twijfel meer.

OUTPUT FORMAT:
{{"action": "BUY/SELL/HOLD", "confidence": 0.0-1.0, "reasoning": "...", "self_doubt": 0.0-1.0}}
"""

    ANALYST_PROMPT_TEMPLATE = """Je bent {agent_name}, een technische analyse expert.

📊 JOUW RECENTE PERFORMANCE (laatste 20 trades):
- Winrate: {winrate:.1%}
- Gemiddelde P&L: {avg_pnl:+.4f}
- Sterkste regime: {best_regime} (winrate: {best_regime_wr:.0%})
- Zwakste regime: {worst_regime} (winrate: {worst_regime_wr:.0%})

🎯 LESSONS LEARNED:
{lessons}

⚠️ LET OP:
Je hebt recentelijk {bias_type}. Pas je aan.

📈 AANPASSING VOOR HUIDIGE MARKT ({regime}):
{adjustment}

💡 OPDRACHT:
Analyseer {symbol} met RSI={rsi}, ADX={adx}, regime={regime}.
Gebruik je historische sterktes en vermijd herhaling van fouten.

OUTPUT FORMAT:
{{"action": "BUY/SELL/HOLD", "confidence": 0.0-1.0, "reasoning": "...", "regime_confidence": 0.0-1.0}}
"""

    @staticmethod
    def build_sentiment_prompt(
        agent_name: str, symbol: str, performance_stats: Dict, recent_trades: List[Dict]
    ) -> str:
        """Build self-improving prompt for sentiment agent."""

        # Calculate bias
        actions = [t["action"] for t in recent_trades]
        action_counts = {}
        for a in actions:
            action_counts[a] = action_counts.get(a, 0) + 1

        if actions and action_counts:
            most_common = max(action_counts.items(), key=lambda x: x[1])
            bias_warning = "Geen significante bias gedetecteerd."

            if most_common[1] / len(actions) > 0.6:
                bias_warning = f"⚠️ WAARSCHUWING: Je geeft {most_common[0]} in {most_common[1]/len(actions)*100:.0f}% van gevallen. Is dit gerechtvaardigd?"

            common_action = most_common[0]
            common_pct = most_common[1] / len(actions) * 100
        else:
            bias_warning = "Nog geen historie beschikbaar."
            common_action = "N/A"
            common_pct = 0

        # Generate reflection text
        if performance_stats["winrate"] > 0.6:
            reflection = "Goede performance! Blijf kritisch en vertrouw niet blind op je succes."
            strategy = "Handhaaf huidige aanpak maar blijf alert voor regime shifts."
            conf_mult = 1.0
        elif performance_stats["winrate"] < 0.4:
            reflection = "Slechte performance recent. Twijfel meer en reduceer position sizes."
            strategy = "Wees conservatiever. Vereis extra confirmatie voor trades."
            conf_mult = 0.7
        else:
            reflection = "Gemiddelde performance. Focus op het vermijden van herhaalde fouten."
            strategy = "Blijf consistent maar analyseer je verliezers kritisch."
            conf_mult = 0.9

        return SelfImprovingPromptBuilder.SENTIMENT_PROMPT_TEMPLATE.format(
            agent_name=agent_name,
            symbol=symbol,
            winrate=performance_stats.get("winrate", 0.5),
            avg_pnl=performance_stats.get("avg_pnl", 0),
            total_trades=performance_stats.get("total", 0),
            common_action=common_action,
            common_pct=common_pct,
            reflection_text=reflection,
            bias_warning=bias_warning,
            strategy_adjustment=strategy,
            confidence_mult=conf_mult,
        )

    @staticmethod
    def build_analyst_prompt(
        agent_name: str,
        symbol: str,
        market_state: Dict,
        performance_stats: Dict,
        regime_performance: Dict,
    ) -> str:
        """Build self-improving prompt for analyst agent."""

        current_regime = market_state.get("regime", "unknown")
        rsi = market_state.get("rsi", 50)
        adx = market_state.get("adx", 20)

        # Find best/worst regimes
        best_regime = (
            max(regime_performance.items(), key=lambda x: x[1]["winrate"])
            if regime_performance
            else ("unknown", {"winrate": 0.5})
        )
        worst_regime = (
            min(regime_performance.items(), key=lambda x: x[1]["winrate"])
            if regime_performance
            else ("unknown", {"winrate": 0.5})
        )

        # Regime-specific adjustment
        current_regime_perf = regime_performance.get(current_regime, {"winrate": 0.5})
        if current_regime_perf["winrate"] > 0.6:
            adjustment = f"Je presteert UITSTEKEND in {current_regime} regime. Wees zelfverzekerd."
        elif current_regime_perf["winrate"] < 0.4:
            adjustment = f"Je hebt MOEITE met {current_regime} regime. Wees extra voorzichtig."
        else:
            adjustment = f"Gemiddelde performance in {current_regime}. Blijf objectief."

        # Lessons based on RSI/ADX performance
        lessons = []
        if rsi < 30:
            lessons.append("Oversold condities (RSI<30) zijn historisch je sterkte.")
        if adx > 30:
            lessons.append("Sterke trends (ADX>30) geven je beste resultaten.")

        lesson_text = (
            " ".join(lessons) if lessons else "Focus op de huidige setup zonder vooroordelen."
        )

        return SelfImprovingPromptBuilder.ANALYST_PROMPT_TEMPLATE.format(
            agent_name=agent_name,
            symbol=symbol,
            winrate=performance_stats.get("winrate", 0.5),
            avg_pnl=performance_stats.get("avg_pnl", 0),
            best_regime=best_regime[0],
            best_regime_wr=best_regime[1]["winrate"],
            worst_regime=worst_regime[0],
            worst_regime_wr=worst_regime[1]["winrate"],
            lessons=lesson_text,
            bias_type=(
                "geen significante bias"
                if performance_stats.get("winrate", 0.5) > 0.4
                else "te weinig twijfel"
            ),
            regime=current_regime,
            adjustment=adjustment,
            rsi=rsi,
            adx=adx,
        )


def generate_agent_reflection(agent_name: str, recent_trades: List[Dict]) -> AgentReflection:
    """
    Generate reflection for an agent based on recent performance.
    In productie: gebruik LLM om dit te genereren.
    """
    if not recent_trades:
        return AgentReflection(
            timestamp=datetime.now().isoformat(),
            agent_name=agent_name,
            recent_winrate=0.5,
            recent_pnl=0.0,
            lessons_learned="Geen historie beschikbaar. Start conservatief.",
            strategy_adjustment="Geen aanpassing nodig.",
            confidence_adjustment=1.0,
            bias_acknowledged=None,
        )

    # Calculate stats
    wins = sum(1 for t in recent_trades if t.get("pnl", 0) > 0)
    winrate = wins / len(recent_trades)
    avg_pnl = sum(t.get("pnl", 0) for t in recent_trades) / len(recent_trades)

    # Detect bias
    actions = [t["action"] for t in recent_trades]
    action_counts = {}
    for a in actions:
        action_counts[a] = action_counts.get(a, 0) + 1

    most_common = max(action_counts.items(), key=lambda x: x[1])
    bias = None
    if most_common[1] / len(actions) > 0.65:
        bias = f"Te veel {most_common[0]} ({most_common[1]/len(actions)*100:.0f}%)"

    # Generate lessons
    if winrate > 0.6:
        lessons = f"Goede run! Winrate {winrate:.0%}. Blijf kritisch."
        adjustment = "Handhaaf strategie, verhoog alleen confidence bij hoge conviction."
        conf_adj = 1.0
    elif winrate < 0.4:
        lessons = f"Slechte run. Winrate {winrate:.0%}. Analyseer je fouten."
        adjustment = "Wees conservatiever. Twijfel meer, verlaag confidence."
        conf_adj = 0.75
    else:
        lessons = f"Gemiddelde performance ({winrate:.0%}). Focus op consistentie."
        adjustment = "Blijf consistent. Identificeer specifieke verbeterpunten."
        conf_adj = 0.9

    if bias:
        lessons += f" Let op: je bent {bias}."
        adjustment += (
            f" Forceer jezelf om meer {['BUY', 'SELL', 'HOLD'] - {most_common[0]}} te overwegen."
        )

    return AgentReflection(
        timestamp=datetime.now().isoformat(),
        agent_name=agent_name,
        recent_winrate=winrate,
        recent_pnl=avg_pnl,
        lessons_learned=lessons,
        strategy_adjustment=adjustment,
        confidence_adjustment=conf_adj,
        bias_acknowledged=bias,
    )
