"""consolidate_models_and_repository

Revision ID: a4af38579884
Revises: 9ae422ce3d22
Create Date: 2026-02-10 21:52:48.498507+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4af38579884"
down_revision: str | None = "9ae422ce3d22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuit_breaker_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("breaker_name", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("trip_reason", sa.String(length=64), nullable=True),
        sa.Column("tripped_at", sa.DateTime(), nullable=True),
        sa.Column("daily_pnl", sa.Float(), nullable=False),
        sa.Column("consecutive_losses", sa.Integer(), nullable=False),
        sa.Column("total_exposure", sa.Float(), nullable=False),
        sa.Column("last_reset_at", sa.DateTime(), nullable=True),
        sa.Column("last_daily_reset_at", sa.DateTime(), nullable=True),
        sa.Column("emergency_shutdown", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_circuit_breaker_state_breaker_name"),
        "circuit_breaker_state",
        ["breaker_name"],
        unique=True,
    )
    op.create_table(
        "decision_audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("observation_data", sa.JSON(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("orientation_data", sa.JSON(), nullable=True),
        sa.Column("market_regime", sa.String(length=32), nullable=True),
        sa.Column("core_sentiment", sa.Float(), nullable=True),
        sa.Column("proposal_data", sa.JSON(), nullable=True),
        sa.Column("proposed_side", sa.String(length=8), nullable=True),
        sa.Column("proposed_size", sa.Float(), nullable=True),
        sa.Column("risk_assessment_data", sa.JSON(), nullable=True),
        sa.Column("risk_decision", sa.String(length=16), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("risk_rationale", sa.Text(), nullable=True),
        sa.Column("execution_data", sa.JSON(), nullable=True),
        sa.Column("execution_status", sa.String(length=32), nullable=True),
        sa.Column("decision_summary", sa.String(length=256), nullable=True),
        sa.Column("trading_mode", sa.String(length=16), nullable=False),
        sa.Column("strategy_id", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_audit_logs_symbol"),
        "decision_audit_logs",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_audit_logs_timestamp"),
        "decision_audit_logs",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_audit_logs_trace_id"),
        "decision_audit_logs",
        ["trace_id"],
        unique=True,
    )
    op.create_table(
        "trading_mode_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("user_role", sa.String(length=32), nullable=False),
        sa.Column("previous_mode", sa.String(length=16), nullable=False),
        sa.Column("new_mode", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trading_mode_changes_timestamp"),
        "trading_mode_changes",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trading_mode_changes_user_id"),
        "trading_mode_changes",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trading_mode_changes_user_id"), table_name="trading_mode_changes")
    op.drop_index(op.f("ix_trading_mode_changes_timestamp"), table_name="trading_mode_changes")
    op.drop_table("trading_mode_changes")
    op.drop_index(op.f("ix_decision_audit_logs_trace_id"), table_name="decision_audit_logs")
    op.drop_index(op.f("ix_decision_audit_logs_timestamp"), table_name="decision_audit_logs")
    op.drop_index(op.f("ix_decision_audit_logs_symbol"), table_name="decision_audit_logs")
    op.drop_table("decision_audit_logs")
    op.drop_index(
        op.f("ix_circuit_breaker_state_breaker_name"),
        table_name="circuit_breaker_state",
    )
    op.drop_table("circuit_breaker_state")
    # ### end Alembic commands ###
