"""add_federated_triad_tables

Revision ID: d8a9e0b6f807
Revises: 418d75e93fe5
Create Date: 2026-02-19 17:27:37.619708+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a9e0b6f807'
down_revision: Union[str, None] = '418d75e93fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'category')
    # ### end Alembic commands ###
