"""add_assets_table

Revision ID: 418d75e93fe5
Revises: fix_audit_ts_tz
Create Date: 2026-02-18 22:18:45.339245+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "418d75e93fe5"
down_revision: str | None = "fix_audit_ts_tz"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DISCOVERED", "ACTIVE", "POOLED", "WATCHED", "INACTIVE", name="assetstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_exchange"), "assets", ["exchange"], unique=False)
    op.create_index(op.f("ix_assets_symbol"), "assets", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assets_symbol"), table_name="assets")
    op.drop_index(op.f("ix_assets_exchange"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
