"""add_risk_settings

Revision ID: 56793ddc083e
Revises: dfc9b5beeeb6
Create Date: 2026-02-06 01:56:54.962807+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56793ddc083e'
down_revision: Union[str, None] = 'dfc9b5beeeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('autonomy_status', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('risk_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'risk_settings')
    op.drop_column('user_preferences', 'autonomy_status')
    # ### end Alembic commands ###
