"""add_runtime_config

Revision ID: f98fcb212619
Revises: a4af38579884
Create Date: 2026-02-10 21:56:03.474672+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f98fcb212619"
down_revision: Union[str, None] = "a4af38579884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_configs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_encrypted", sa.Boolean(), nullable=True),
        sa.Column("group", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_runtime_configs_group"), "runtime_configs", ["group"], unique=False
    )
    op.create_index(
        op.f("ix_runtime_configs_key"), "runtime_configs", ["key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runtime_configs_key"), table_name="runtime_configs")
    op.drop_index(op.f("ix_runtime_configs_group"), table_name="runtime_configs")
    op.drop_table("runtime_configs")
    # ### end Alembic commands ###
