"""add_persistent_learning

Revision ID: d8fce2b4fe40
Revises: 8fa01144a921
Create Date: 2026-02-06 02:09:52.047339+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8fce2b4fe40"
down_revision: Union[str, None] = "8fa01144a921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # try:
    #     op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;") # Enable TimescaleDB
    # except Exception as e:
    #     print(f"WARNING: Could not enable timescaledb extension. Skipping hypertable creation. Error: {e}")

    op.create_table(
        "agent_experiences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state_vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "next_state_vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("action", sa.Integer(), nullable=False),
        sa.Column("reward", sa.Float(), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.Column("meta_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_experiences_agent_id"),
        "agent_experiences",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_experiences_timestamp"),
        "agent_experiences",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "market_candles",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("symbol", "timeframe", "timestamp"),
    )
    op.create_index(
        op.f("ix_market_candles_symbol"), "market_candles", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_market_candles_timestamp"),
        "market_candles",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "market_ticks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("side", sa.String(), nullable=True),
        sa.Column("exchange_sequence", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", "timestamp"),  # Composite PK for TimescaleDB
    )
    op.create_index(
        op.f("ix_market_ticks_symbol"), "market_ticks", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_market_ticks_timestamp"), "market_ticks", ["timestamp"], unique=False
    )

    # Convert to Hypertables
    # try:
    #     op.execute("SELECT create_hypertable('market_candles', 'timestamp', chunk_time_interval => interval '1 day', if_not_exists => TRUE);")
    #     op.execute("SELECT create_hypertable('market_ticks', 'timestamp', chunk_time_interval => interval '1 hour', if_not_exists => TRUE);")
    # except Exception as e:
    #     print(f"WARNING: Could not create hypertables (TimescaleDB not active). Error: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_ticks_timestamp"), table_name="market_ticks")
    op.drop_index(op.f("ix_market_ticks_symbol"), table_name="market_ticks")
    op.drop_table("market_ticks")
    op.drop_index(op.f("ix_market_candles_timestamp"), table_name="market_candles")
    op.drop_index(op.f("ix_market_candles_symbol"), table_name="market_candles")
    op.drop_table("market_candles")
    op.drop_index(
        op.f("ix_agent_experiences_timestamp"), table_name="agent_experiences"
    )
    op.drop_index(op.f("ix_agent_experiences_agent_id"), table_name="agent_experiences")
    op.drop_table("agent_experiences")
    # ### end Alembic commands ###
